spring.application.name=firstspringproject
spring.datasource.url=jdbc:postgresql://localhost:5432/testdatabase
spring.datasource.username=test
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update