spring.application.name=firstspringproject

spring.datasource.url=jdbc:postgresql://database-1.cfiggamwa10n.eu-north-1.rds.amazonaws.com:5432/postgres?sslmode=require
spring.datasource.username=postgres
spring.datasource.password=Tech#2026!
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

jwt.secret=dGhpcyBpcyBhIHNlY3JldCBrZXkgZm9yIEpXVCB0b2tlbiBzaWduaW5n
